version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
workflows:
  build_and_test:
    jobs:
      - build
